Kotik98 base64
tehnotrack/track18-spring pull request #68
Opened 2018-03-07 15:22 UTC by kotik98

2018-04-18 17:55 UTC, darkwrat requested changes
жду исправлений

2018-04-18 17:55 UTC, darkwrat commented on L1-intro/src/main/java/ru/track/App.java
>  }
этот мерджреквест посвящен задаче base64, посему лишние изменения отсюда надо спилить

2018-04-18 17:55 UTC, darkwrat commented on L1-intro/src/main/java/ru/track/App2.java
> +        System.out.println(Arrays.toString(args));
лишнее

2018-04-18 17:55 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +        //finPath = "C:\\Users\\zahar\\git\\track18-spring\\L2-objects\\image_256.png";
зачем здесь этот коммент?

2018-04-18 17:55 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +        int bufferSize = 16002;
а что это за магическая константа и зачем резервировать столько памяти?

2018-04-18 17:55 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +        inputStream.close();
если какой read выкинет исключение -- стрим не закроется. нужно использовать try-with-resources

2018-04-18 17:55 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +        StringBuilder result = new StringBuilder();
задачу можно решить с константным потреблением памяти, не буферизовать целиком входные и выходные данные

2018-06-11 21:14 UTC, kotik98 commented
исправил

2018-06-21 16:45 UTC, darkwrat commented
принято

2018-06-21 16:45 UTC, closed without merging