mikhan333-base64
tehnotrack/track18-spring pull request #78
Opened 2018-03-08 12:21 UTC by mikhan333

2018-04-18 17:50 UTC, darkwrat commented
всё хорошо, но есть проблемы с буферизацией при чтении входного файла. он читается по 3 байта на сисколл, в итоге при какой-либо вменяемой нагрузке машина уходит в sys% cpu
> strace -f -e trace=read,write mvn -Dexec.args="/home/m.galaganov/boroda.jpg" -Dexec.mainClass="ru.track.io.TaskImplementation" exec:java

видно 
[pid 26507] read(83, "N\257\375", 3)    = 3
[pid 26507] read(83, "3cO", 3)          = 3
[pid 26507] read(83, "\375\"\224", 3)   = 3
[pid 26507] read(83, "\177\302\343", 3) = 3
[pid 26507] read(83, "# \310", 3)       = 3
[pid 26507] read(83, "\212\340y", 3)    = 3
[pid 26507] read(83, "\r\r\376", 3)     = 3
[pid 26507] read(83, "\t\257\223", 3)   = 3
[pid 26507] read(83, "\240\303q", 3)    = 3
[pid 26507] read(83, "\306|j", 3)       = 3
[pid 26507] read(83, "\377\0\244", 3)   = 3
[pid 26507] read(83, "r\217\370", 3)    = 3
[pid 26507] read(83, "\\jo", 3)         = 3
[pid 26507] read(83, "\360L|", 3)       = 3
[pid 26507] read(83, "\234\346\33", 3)  = 3
[pid 26507] read(83, "\2164\343", 3)    = 3
[pid 26507] read(83, "_\375#", 3)       = 3
[pid 26507] read(83, "\224\177\302", 3) = 3
[pid 26507] read(83, "\343#!", 3)       = 3
[pid 26507] read(83, "\300W1", 3)       = 3
[pid 26507] read(83, "\237\371%", 3)    = 3

2018-04-18 17:51 UTC, darkwrat requested changes
жду исправления ситуации с потреблением проца в системных вызовах

2018-04-22 19:29 UTC, mikhan333 commented
Исправил

2018-05-11 15:49 UTC, darkwrat commented
принято

2018-05-11 15:49 UTC, closed without merging